ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1
country=SK

network={
	ssid="stradiot-dmz"
	psk=f3d235add1fa5360a65644bbd0d012c3f61ac4206433ce3d4d7f898f4e83a4a1
	priority=10
}
