MACHINE = "raspberrypi4-64"
DISTRO = "poky"

LICENSE_FLAGS_ACCEPTED += " \
    Firmware-broadcom_bcm43xx-rpidistro \
    binary-redist-Cypress-rpidistro \
    synaptics-killswitch \
"

DL_DIR ?= "${TOPDIR}/../downloads"
SSTATE_DIR ?= "${TOPDIR}/../sstate-cache"

BB_LOG_CONFIG = "debug"
BB_LOG_FILENAME = "${TMPDIR}/debug_parsing.log"

ENABLE_UART = "1"
ENABLE_KGBD = "1"

INIT_MANAGER = "systemd"
NETWORK_MANAGER = "networkmanager"

DISTRO_FEATURES:append = " wifi dbus"
IMAGE_INSTALL:append = " \
    linux-firmware-rpidistro-bcm43455 \
    networkmanager \
    iw \
    packagegroup-base-extended \
    kernel-modules \
"
